application/models/User.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class User extends ActiveRecord implements IdentityInterface
{
    public static function tableName()
    {
        return 'users';
    }

    public function attributeLabels()
    {
        return [
            'username' => 'Логин',
            'password' => 'Пароль',
        ];
    }

    public function rules()
    {
        return [
            [['username', 'password'], 'required', 'on' => 'register'],
            ['username', 'unique', 'on' => 'register'],

            ['username', 'required', 'on' => 'login', 'message' => 'Проверьте правильность логина'],
            ['password', 'required', 'on' => 'login', 'message' => 'Неверный пароль'],

            [['username', 'password'], 'trim'],
            [['username', 'password'], 'string'],
        ];
    }

    public function beforeSave($insert)
    {
        if (!isset($this->id)) {
            $this->password = \Yii::$app->security->generatePasswordHash($this->password);
        }

        return true;
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }
} 

application/controllers/IndexController.php
<?php

namespace app\controllers;

use yii\web\Controller;

class IndexController extends Controller
{
    public function actionIndex()
    {
        $this->view->title = 'Главная страница';
        echo $this->render('index');
    }
}

application/controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use yii\bootstrap\ActiveForm;
use app\models\User;
use app\components\Paypal;

class UserController extends Controller
{
    /**
     * @var Paypal
     */
    protected $paypal;

    public function init()
    {
        $this->paypal = \Yii::$app->paypal;
    }

    public function actionAuth()
    {
        $result = [];

        if (!\Yii::$app->user->isGuest) {
            return $this->redirect('/');
        }
        $model = new User();
        $model->setScenario('login');

        if (\Yii::$app->request->isPost) {

            $userData = \Yii::$app->request->post('User');
            $identity = User::findOne(['username' => $userData['username']]);

            if ($identity) {
                if (!empty($userData['password'])) {
                    if (\Yii::$app->security->validatePassword($userData['password'], $identity->password)) {
                        \Yii::$app->user->login($identity);
                        return $this->redirect('/');
                    } else {
                        $result['user-password'] = ['Неверный пароль'];
                    }
                } else {
                    $result['user-password'] = ['Неверный пароль'];
                }
            } else {
                $result['user-username'] = ['Проверьте правильность логина'];
            }

            if (\Yii::$app->request->isAjax) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                return $result;
            }
        }

        if (\Yii::$app->request->isAjax) {
            echo $this->renderAjax('auth', [
                'model' => $model
            ]);
        } else {
            echo $this->render('auth', [
                'model' => $model
            ]);
        }
    }

    public function actionRegister()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect('/');
        }
        $model = new User();
        $model->setScenario('register');

        if (\Yii::$app->request->isPost) {

            $userData = \Yii::$app->request->post('User');
            $model->setAttributes($userData);

            if (\Yii::$app->request->post('reg', false)) {
                if ($model->save()) {
                    \Yii::$app->user->login($model);
                }
            }
        }
        return $this->redirect('/');
    }

    public function actionRegisterValidate()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        if (\Yii::$app->request->isAjax) {

            if (\Yii::$app->user->isGuest) {
                $model = new User();
                $model->setScenario('register');
                $model->load(\Yii::$app->request->post());
                return ActiveForm::validate($model);
            }
        }
        return [];
    }

    public function actionLogout()
    {
        if (!\Yii::$app->user->isGuest) {
            \Yii::$app->user->logout();
        }
        return $this->redirect('/');
    }

    public function actionPay()
    {
        if (!Yii::$app->user->isGuest) {
            try {
                /*
                 * make payment transaction
                 */
                $payment = $this->paypal->makePayment();

                if ($payment) {
                    return $this->redirect($payment->getApprovalLink());
                }
            } catch (\Exception $e) {}
        }
        return $this->redirect('/');
    }

    public function actionSuccess($paymentId, $token, $PayerID)
    {
        $this->view->title = 'Поздравляем!';

        if (!Yii::$app->user->isGuest) {
            try {
                /*
                 * Process and approve payment.
                 * And save payment information to user attributes.
                 */
                $payment = $this->paypal->processPayment($paymentId, $PayerID);
                if ($payment->state == 'approved') {
                    /**
                     * @var User $user
                     */
                    $user = \Yii::$app->user->getIdentity();
                    $user->paid = 1;
                    $user->paymentId = $paymentId;
                    $user->save();
                    return $this->render('success', []);
                }
            } catch (\Exception $e) {}
        }
        return $this->redirect('/');
    }

    public function actionFail()
    {
        $this->view->title = 'Ошибка';
        return $this->render('/index/index');
    }

    public function actionDownload()
    {
        if (!Yii::$app->user->isGuest) {
            $user = Yii::$app->user->getIdentity();
            if ($user->paid) {
                $path = \Yii::getAlias('@app/../files/file.zip');
                $file = realpath($path);
                if (file_exists($file)) {
                    return \Yii::$app->response->sendFile($file);
                }
            }
        }
        return $this->redirect('/');
    }
}

application/views/index/index.php
<?php

use yii\helpers\Url;
use yii\bootstrap\Html;

?>
<div class="container">
    <div class="row">
        <div class="text-center">
            <div class="jumbotron">
                <h1>Добро пожаловать!</h1>
                <p>Мы рады представить Вам наш новый zip-архив.</p>
                <p>Только сегодня действует специальная цена - $1.</p>
            </div>
        </div>

        <?php if (Yii::$app->user->isGuest) : ?>
            <div class="well text-center">
                <?=Html::a('Авторизируйтесь', Url::toRoute('user/auth'), [
                    'data-toggle' => 'modal',
                    'data-target' => '#modal'
                ])?>, чтоб оплатить и скачать архив.
            </div>
        <?php else : ?>
            <?php
            $user = Yii::$app->user->getIdentity();
            if ($user->paid) : ?>
                <p class="text-center">Вы можете <a href="/user/download/">скачать архив</a>.</p>
            <?php else : ?>
                <p class="text-center">
                    <a href="<?=Url::toRoute(['user/pay'])?>">
                        <img src="https://www.paypalobjects.com/webstatic/en_US/i/btn/png/gold-pill-paypal-60px.png" alt="PayPal">
                    </a>
                </p>
            <?php endif; ?>
        <?php endif; ?>

    </div>
</div>

<div class="modal fade" id="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>

application/views/layouts/main.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

/**
 * @var \yii\web\View $this
 */

$this->beginPage();

?>
<!doctype html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="<?= Yii::$app->charset; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <?= Html::csrfMetaTags(); ?>
        <title><?= Html::encode($this->title . ' - Merchant'); ?></title>
        <?php $this->head(); ?>
    </head>
    <body>
        <?php $this->beginBody(); ?>
        <header>
            <?php

            NavBar::begin([
                'brandLabel' => 'Merchant',
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top'
                ]
            ]);
                echo Nav::widget([
                    'items' => [
                        ['label' => 'Войти', 'url' => ['user/auth'], 'linkOptions' => [
                            'data-toggle' => 'modal',
                            'data-target' => '#modal'
                        ], 'visible' => Yii::$app->user->isGuest],
                        ['label' => 'Выйти', 'url' => ['user/logout'], 'visible' => !Yii::$app->user->isGuest],
                    ],
                    'options' => ['class' => 'navbar-nav navbar-right'],
                ]);
            NavBar::end();

            ?>
        </header>
        <main style="padding-top: 80px">
            <?= $content; ?>
        </main>
        <footer></footer>

        <?php $this->endBody(); ?>
    </body>
</html>
<?php $this->endPage(); ?>

application/views/user/auth.php
<?php

use \yii\bootstrap\Html;
use \yii\bootstrap\ActiveForm;

?>
<div id="forms" class="carousel slide">
    <div class="carousel-inner">
        <div class="item active">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Авторизация</h4>
            </div>
            <div class="modal-body">
                <?php

                $form = ActiveForm::begin([
                    'id' => 'auth-form',
                    'action' => 'user/auth/',
                    'layout' => 'horizontal',
                    'enableAjaxValidation' => true,
                    'validationUrl' => '/user/auth/',
                ]);

                echo $form->field($model, 'username');
                echo $form->field($model, 'password')->passwordInput();
                ?>

                <p class="text-center">Если у Вас нет аккаунта, Вы можете <?=Html::a('зарегистрироваться', '#', [
                        'data-target' => '#forms',
                        'data-slide-to' => "1",
                    ])?></p>

                <hr/>
                <div class="pull-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary">Войти</button>
                </div>
                <div class="clearfix"></div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <div class="item">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Регистрация</h4>
            </div>
            <div class="modal-body">
                <?php

                $form = ActiveForm::begin([
                    'id' => 'reg-form',
                    'action' => 'user/register/',
                    'layout' => 'horizontal',
                    'enableAjaxValidation' => true,
                    'validationUrl' => '/user/register-validate/',
                ]);

                echo $form->field($model, 'username');
                echo $form->field($model, 'password')->passwordInput();
                ?>

                <p class="text-center">Если у Вас уже есть аккаунт, Вы можете <?=Html::a('авторизироваться', '#', [
                        'data-target' => '#forms',
                        'data-slide-to' => "0",
                    ])?></p>

                <hr/>
                <div class="pull-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary" name="reg" value="1">Зарегистрироваться</button>
                </div>
                <div class="clearfix"></div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

application/views/user/success.php
<div class="container">
    <div class="row">
        <div class="col-xs-12 text-center">

            <h1>Поздравляем!</h1>

            <p>Теперь Вы можете <a href="/user/download/">скачать архив</a>.</p>

        </div>

    </div>
</div>